repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files

-   repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        name: "yapf"
        args: ["--style={based_on_style: yapf, indent_width: 4, column_limit: 99, split_before_logical_operator: false, arithmetic_precedence_indication: true, split_before_arithmetic_operator: true}"]



# flake8 is a Python linting tool that wraps PyFlakes, pycodestyle, and mccabe.
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [
        "--max-line-length=99",
        "--extend-ignore", "F821,F722,E203",
        "--per-file-ignores=__init__.py:F401"

        ]

# isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections and by type.
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"] # I'm not actually sure what filter-files does, but it seems to work


# Custom local hook for clearing Jupyter notebook outputs
-   repo: local
    hooks:
      - id: clear-notebook-output
        name: Clear Jupyter Notebook Outputs
        entry: bash -c 'for f in $(git diff --name-only --cached); do if [[ $f == *.ipynb ]]; then jupyter nbconvert --clear-output --inplace $f && git add $f; fi; done'
        language: system
        types: [jupyter]

      #- id: build-sphinx-docs
      #  name: Build Sphinx Documentation
      #  entry: bash -c 'cd docs && make html'
      #  language: system
      #  pass_filenames: false
      #  always_run: true
