# Config for the VQ-VAE model
name: final_final_revert_default

model:
  quantization_mode: default
  disable_neck: true
  n_vertices: 5443

training:
  epochs: 200
  base_lr: 0.0001
  # base_lr: 0.001

compile: false
