# Config for the VQ-VAE model
name: vertex_baseline

model:
  quantization_mode: default
  disable_neck: true
  n_vertices: 5443
  use_flame_code: false


training:
  epochs: 200
  # base_lr: 0.0001
  base_lr: 0.001

compile: false
