# audio to vertices prediction

name: baseline_vertex_prediction

model:
  # vq_vae_pretrained_path: tb_logs/vector_quantization/default_flame/version_0/checkpoints/epoch=199-step=15400.ckpt
  # vq_vae_pretrained_path: tb_logs/vector_quantization/default_flame/version_1/checkpoints/epoch=199-step=15400.ckpt
  # vq_vae_pretrained_path: tb_logs/vector_quantization/default_flame_vertex_loss/version_2/checkpoints/epoch=199-step=15400.ckpt
  vq_vae_pretrained_path: tb_logs/vector_quantization/vertex_baseline/version_0/checkpoints/epoch=199-step=15400.ckpt
training: {}

compile: False
