# audio to vertices prediction

name: new_flame_driven

model:
  vq_vae_pretrained_path: tb_logs/vector_quantization/new_flame_driven/version_0/checkpoints/epoch=199-step=15400.ckpt
  feature_dim: 1024
  num_layers: 3

training:
  epochs: 100
  base_lr: 1e-5

compile: False

# maybe add another lip specific loss
# maybe add windowed sub sampling
