# Config for the VQ-VAE model
name: new_flame_driven

model:
  quantization_mode: default
  disable_neck: true
  n_vertices: 5443
  face_quan_num: 1
  flame_mode: flame
  use_audio: false


training:
  epochs: 200
  base_lr: 0.0001
  use_other_guy: false

compile: false
