# audio to vertices prediction

name: prediction_flame_default

model:
  # vq_vae_pretrained_path: tb_logs/vector_quantization/without_neck_fsq/version_0/checkpoints/epoch=199-step=15400.ckpt
  # vq_vae_pretrained_path: tb_logs/vector_quantization/without_neck_default/version_16/checkpoints/epoch=199-step=15400.ckpt
  # vq_vae_pretrained_path: tb_logs/vector_quantization/without_neck_default/version_17/checkpoints/epoch=199-step=15400.ckpt
  # vq_vae_pretrained_path: tb_logs/vector_quantization/without_neck_fsq/version_2/checkpoints/epoch=199-step=15400.ckpt
  vq_vae_pretrained_path: tb_logs/vector_quantization/default_flame/version_0/checkpoints/epoch=199-step=15400.ckpt

training: {}

compile: False
