# ===== Configuration for single-frame training =====
name: 3dgs

# ---> gaussian splatting settings
gaussian_splatting_settings:

  # pre-processing settings
  use_view_dependent_color_mlp: true
  rasterization_mode: 3dgs

  # rasterization_settings
  sh_degree: 3

  # post-processing settings
  # background_r: 0.66
  # background_g: 0.66
  # background_b: 0.66
  background_r: 0.0
  background_g: 0.0
  background_b: 0.0
  screen_space_denoising_mode: none
  learnable_color_correction: false

  # densification_settings
  densification_mode: monte_carlo_markov_chain
  # densification_mode: default
  refine_start_iteration: 500
  refine_stop_iteration: 90_000
  cap_max: 100_000

  # initialization settings
  # initialization_mode: point_cloud
  # initialization_mode: random
  initialization_mode: flame
  initialization_points: 30_000

  # losses
  l1_image_loss: 1.0
  ssim_image_loss: 0.1
  ssim_denoised_image_loss: null
  lpips_image_loss: 0.05
  anisotropy_loss: 0.1
  max_scale_loss: 10.0
  local_rigidity_loss: null
  background_loss: 0.1
  dist_loss: 10.0
  # dist_loss: null
  # region specific losses
  hair_l1_loss: 0.0
  hair_ssim_loss: 0.1 # effectively doubles the ssim loss in hair regions
  eyebrows_l1_loss: 0.0
  eyebrows_ssim_loss: 0.1
  lips_l1_loss: 0.0
  lips_ssim_loss: 0.1
  neck_l1_loss: 0.0
  inner_mouth_l1_loss: 0.0
  inner_mouth_ssim_loss: 0.1

  # kwargs
  lpips_network: 'alex'

  # train settings
  feature_dim: 32
  camera_batch_size: 1
  train_iterations: 100_000
  log_images_interval: 500

# ---> Learning Rates
learning_rates:
  # 3D Splatting
  means_lr: 1.6e-4
  scales_lr: 5e-3
  quats_lr: 1e-3
  opacities_lr: 5e-2
  features_lr: 2.5e-3
  # colors
  sh0_lr: 2.5e-3 # shN is 1/20 of sh0
  color_lr: 2.5e-3

  # Color MLP
  color_mlp_lr: 1e-3
  color_mlp_weight_decay: 1e-6
  # Color Correction
  color_correction_lr: 1e-5

# ---> Random other stuff
compile: true
viewer_port: 8080
sequence: 3
frame: 42
num_train_workers: 12
num_val_workers: 4
tensorboard_dir: logs
enable_viewer: true
