# ===== Configuration for single-frame training =====
name: debugging

# ---> gaussian splatting settings
gaussian_splatting_settings:

  # pre-processing settings
  use_view_dependent_color_mlp: true
  rasterization_mode: 3dgs
  dist_loss: false # 2dgs only

  # rasterization_settings
  sh_degree: 3

  # post-processing settings
  background_r: 0.5
  background_g: 0.5
  background_b: 0.5
  screen_space_denoising_mode: none

  # densification_settings
  densification_mode: monte_carlo_markov_chain
  # densification_mode: default
  refine_start_iteration: 500
  refine_stop_iteration: 25_000
  cap_max: 100_000

  # initialization settings
  # initialization_mode: point_cloud
  initialization_mode: random
  initialization_points: 30_000

  # losses
  l1_image_loss: 1.0
  ssim_image_loss: 0.1
  ssim_denoised_image_loss: null
  lpips_image_loss: null # 0.05
  anisotropy_loss: 0.1
  max_scale_loss: 10.0
  local_rigidity_loss: null
  background_loss: 0.1

  # train settings
  feature_dim: 32
  camera_batch_size: 4
  train_iterations: 30_000
  log_images_interval: 500

# ---> Learning Rates
learning_rates:
  # 3D Splatting
  means_lr: 1.6e-4
  scales_lr: 5e-3
  quats_lr: 1e-3
  opacities_lr: 5e-2
  features_lr: 2.5e-3
  # colors
  sh_0_lr: 2.5e-3
  sh_N_lor: 1.25e-4 # i.e. 1/20 of sh_0_lr
  # Color MLP
  color_mlp_lr: 1e-3
  color_mlp_weight_decay: 1e-6

# ---> Random other stuff
compile: false
viewer_port: 8080
sequence: 3
frame: 42
num_train_workers: 12
tensorboard_dir: logs
enable_viewer: true
